# Generated by Django 4.2.6 on 2024-09-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallerie_Bilder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('image8', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('image9', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('image10', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('image11', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('image12', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('image13', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
    ]
