# Generated by Django 4.1.7 on 2024-09-16 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerie_bilder',
            name='image10',
        ),
        migrations.RemoveField(
            model_name='gallerie_bilder',
            name='image11',
        ),
        migrations.RemoveField(
            model_name='gallerie_bilder',
            name='image12',
        ),
        migrations.RemoveField(
            model_name='gallerie_bilder',
            name='image13',
        ),
        migrations.RemoveField(
            model_name='gallerie_bilder',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='gallerie_bilder',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='gallerie_bilder',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='gallerie_bilder',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='gallerie_bilder',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='gallerie_bilder',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='gallerie_bilder',
            name='image8',
        ),
        migrations.RemoveField(
            model_name='gallerie_bilder',
            name='image9',
        ),
    ]
