# Generated by Django 4.1.7 on 2024-09-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_gallerie_bilder_image10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerie_bilder',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
