# Generated by Django 4.1.7 on 2024-09-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_gallerie_bilder_image10_gallerie_bilder_image11_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerie_bilder',
            name='image14',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='gallerie_bilder',
            name='image15',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
