# Generated by Django 4.1.7 on 2024-09-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_gallerie_bilder_image14_gallerie_bilder_image15'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerie_bilder',
            name='image10',
        ),
        migrations.RemoveField(
            model_name='gallerie_bilder',
            name='image11',
        ),
        migrations.RemoveField(
            model_name='gallerie_bilder',
            name='image12',
        ),
        migrations.RemoveField(
            model_name='gallerie_bilder',
            name='image13',
        ),
        migrations.RemoveField(
            model_name='gallerie_bilder',
            name='image14',
        ),
        migrations.RemoveField(
            model_name='gallerie_bilder',
            name='image15',
        ),
        migrations.RemoveField(
            model_name='gallerie_bilder',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='gallerie_bilder',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='gallerie_bilder',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='gallerie_bilder',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='gallerie_bilder',
            name='image8',
        ),
        migrations.RemoveField(
            model_name='gallerie_bilder',
            name='image9',
        ),
        migrations.AddField(
            model_name='gallerie_bilder',
            name='kategorija',
            field=models.CharField(choices=[('kupatilo', 'Kupatilo'), ('wc', 'WC'), ('balkoni', 'Balkoni')], default='kupatilo', max_length=20),
        ),
        migrations.AlterField(
            model_name='gallerie_bilder',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
