# Generated by Django 4.2.6 on 2024-09-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_remove_gallerie_bilder_image10_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerie_bilder',
            name='kategorija',
        ),
        migrations.AddField(
            model_name='gallerie_bilder',
            name='category',
            field=models.CharField(choices=[('WC', 'WC'), ('Kupatilo', 'Kupatilo'), ('Balkon', 'Balkon')], default='WC', max_length=50),
        ),
        migrations.AddField(
            model_name='gallerie_bilder',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='gallerie_bilder',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='gallerie_bilder',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
