# Generated by Django 4.1.7 on 2024-09-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_remove_gallerie_bilder_kategorija_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerie_bilder',
            name='category',
        ),
        migrations.AddField(
            model_name='gallerie_bilder',
            name='image10',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='gallerie_bilder',
            name='image11',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='gallerie_bilder',
            name='image12',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='gallerie_bilder',
            name='image13',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='gallerie_bilder',
            name='image14',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='gallerie_bilder',
            name='image15',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='gallerie_bilder',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='gallerie_bilder',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='gallerie_bilder',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='gallerie_bilder',
            name='image9',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
