# Generated by Django 4.1.7 on 2024-09-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_remove_gallerie_bilder_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='kupatilo/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='kupatilo/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='kupatilo/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='kupatilo/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='kupatilo/')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='kupatilo/')),
            ],
        ),
        migrations.CreateModel(
            name='BalkonTerasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='balkon_terasa/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='balkon_terasa/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='balkon_terasa/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='balkon_terasa/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='balkon_terasa/')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='balkon_terasa/')),
            ],
        ),
        migrations.CreateModel(
            name='Flur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='hodnik/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='hodnik/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='hodnik/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='hodnik/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='hodnik/')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='hodnik/')),
            ],
        ),
        migrations.CreateModel(
            name='Umbau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='umbau/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='umbau/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='umbau/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='umbau/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='umbau/')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='umbau/')),
            ],
        ),
        migrations.CreateModel(
            name='WC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='wc/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='wc/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='wc/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='wc/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='wc/')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='wc/')),
            ],
        ),
        migrations.DeleteModel(
            name='Gallerie_Bilder',
        ),
    ]
