# Generated by Django 4.1.7 on 2024-09-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_bad_balkonterasse_flur_umbau_wc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Küche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='kuhinja/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='kuhinja/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='kuhinja/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='kuhinja/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='kuhinja/')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='kuhinja/')),
            ],
        ),
        migrations.CreateModel(
            name='WC_Bad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='wc/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='wc/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='wc/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='wc/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='wc/')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='wc/')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='wc/')),
                ('image8', models.ImageField(blank=True, null=True, upload_to='wc/')),
            ],
        ),
        migrations.DeleteModel(
            name='Bad',
        ),
        migrations.DeleteModel(
            name='WC',
        ),
        migrations.AddField(
            model_name='balkonterasse',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='balkon_terasa/'),
        ),
        migrations.AddField(
            model_name='balkonterasse',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='balkon_terasa/'),
        ),
        migrations.AddField(
            model_name='umbau',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='umbau/'),
        ),
        migrations.AddField(
            model_name='umbau',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='umbau/'),
        ),
    ]
